channels:
    - conda-forge

dependencies:
    - python=3.6
    - numpy=1.17.3
    - scipy=1.3.2
    - matplotlib=3.1.2
    - pandas=0.25.3
    - sympy=1.4
    - jupyterlab=1.2.3
    - notebook=6.0.1
    - ipywidgets=7.5.1
    - tifffile=2019.7.26
    - tqdm=4.38.0
    - scikit-image=0.16.2
    - openjdk=11.0.1
    - pyimagej=0.4.0
    - pillow=6.2.1
    - joblib=0.14.0
